# torchtitan Config.toml
# Llama 1B test run on Leonardo using local FineWeb-Edu data

[job]
dump_folder = "./outputs"
description = "Llama 1B test run on Leonardo with fw-edu"
print_args = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 1000
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = true
save_tb_folder = "tb"
enable_wandb = true
save_for_all_ranks = false
log_param_norms = true
log_param_norms_freq = 500

[model]
name = "boom"
freq_nope = 4
use_qk_norm = true
flavor = "1B"
tokenizer_path = "./assets/tokenizer/Llama-3.2-1B"
use_flex_attn = true
attn_mask_type = "document_causal"
eos_id = 128001

[optimizer]
name = "AdamW"
beta_1 = 0.9
beta_2 = 0.95
lr = 0.0002
eps = 1e-8
optim_implementation = "fused"
wd_embeddings = false
wd_norm = true
wd_qknorm = true

[lr_scheduler]
warmup_steps = 10
decay_ratio = 0
decay_type = "linear"
min_lr_factor = 0.0

[training]
local_batch_size = 1
seq_len = 4096
max_norm = 1.0
steps = 20
compile = true
seed = 6
deterministic = false
dataset_type = "huggingface"
dataset = "fineweb-edu-10bt"
dataset_path = "/leonardo_work/IscrB_Decentro/mciccone/sl3/datasets/fw-edu/sample/10BT"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default"
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval = 1000
last_save_model_only = false
export_dtype = "float32"
async_mode = "disabled"

[activation_checkpoint]
mode = "none"

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enabled = false
dataset = "c4_validation"
freq = 5
steps = 100
